# Generated by Django 3.2 on 2021-04-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('age', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pokemon', models.CharField(max_length=200)),
                ('happiness', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hunger', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
