# Generated by Django 3.2 on 2021-05-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210503_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokemon',
            field=models.CharField(choices=[('Bulbasaur', 'Bulbasaur'), ('Squirtle', 'Squirtle'), ('Charmander', 'Charmander')], default='Bulbasaur', max_length=200),
        ),
    ]
