# Generated by Django 3.2 on 2021-05-04 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_pokemon_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='func_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
