# Generated by Django 3.2 on 2021-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pokemon_func_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
